#!/usr/bin/env python3
"""
Regenerate README.md from all *_viz.html files in this directory.

Usage:
    python generate_readme.py
"""

import json
import re
from pathlib import Path

VIZ_DIR = Path(__file__).resolve().parent


def extract_cfg(html_path):
    with open(html_path) as f:
        c = f.read()
    m = re.search(r'const CFG = (\{.*?\});', c, re.DOTALL)
    if not m:
        return None, None
    cfg = json.loads(m.group(1))
    pm = re.search(r'Total Params</span> <span class="font-mono [^"]*">([^<]+)</span>', c)
    params_str = pm.group(1) if pm else "?"
    return cfg, params_str


def shorten_params(params_str):
    if "(" in params_str:
        return params_str.split("(")[-1].rstrip(")")
    return params_str


def get_group(stem):
    if stem.startswith("Qwen_Qwen") or "DeepSeek-R1" in stem:
        return "qwen"
    if stem.startswith("google_"):
        return "google"
    if stem.startswith("deepseek-ai_"):
        return "deepseek"
    if stem.startswith("nvidia_") or stem.startswith("tencent_"):
        return "nvidia"
    if stem.startswith("microsoft_"):
        return "microsoft"
    return "other"


def get_attn(cfg):
    if cfg.get("is_mqa"):
        return "MQA"
    if cfg.get("is_gqa"):
        return f"GQA {cfg.get('gqa_ratio', 0)}:1"
    return "MHA"


def clean_name(stem):
    display = stem.replace("_", " ")
    for prefix in ["Qwen ", "google ", "deepseek-ai ", "microsoft ", "nvidia NVIDIA ",
                   "nvidia ", "tencent ", "moonshotai ", "HuggingFaceTB ", "allenai ",
                   "THUDM ", "ai-sage ", "openbmb ", "MiniMaxAI ", "poolside ",
                   "SupraLabs ", "InternScience ", "zai-org ", "baidu ",
                   "meituan-longcat ", "deepreinforce-ai "]:
        if display.startswith(prefix):
            return display[len(prefix):]
    return display


def collect_models():
    rows = []
    for f in sorted(VIZ_DIR.glob("*_viz.html")):
        cfg, params_str = extract_cfg(f)
        if not cfg:
            continue
        stem = f.stem.replace("_viz", "")
        params_short = shorten_params(params_str)
        rows.append({
            "file": f.name,
            "name": clean_name(stem),
            "type": cfg.get("model_type", "?"),
            "params": params_str,
            "params_short": params_short,
            "H": cfg.get("hidden_size", 0),
            "layers": cfg.get("num_layers", 0),
            "heads": f'{cfg.get("num_heads", 0)}/{cfg.get("num_kv_heads", 0)}',
            "head_dim": cfg.get("head_dim", 0),
            "attn": get_attn(cfg),
            "qk": "Y" if cfg.get("has_qk_norm") else "-",
            "mlp": cfg.get("mlp_type", "?"),
            "moe": f'{cfg.get("num_experts", 0)} exp' if cfg.get("is_moe") else "-",
            "rope": f'{cfg.get("rope_theta", 0):,.0f}' if cfg.get("rope_theta") else "-",
            "vocab": f'{cfg.get("vocab_size", 0):,}',
            "tie": "Y" if cfg.get("tie_embeddings") else "-",
            "group": get_group(stem),
        })
    # Hand-crafted reference
    rows.append({
        "file": "qwen3_0_6b_architecture_visualizer.html",
        "name": "Qwen3-0.6B (hand-crafted)", "type": "qwen3",
        "params": "600,651,776 (600.7M)", "params_short": "600.7M",
        "H": 1024, "layers": 28, "heads": "16/8", "head_dim": 128,
        "attn": "GQA 2:1", "qk": "Y", "mlp": "SwiGLU", "moe": "-",
        "rope": "1,000,000", "vocab": "151,936", "tie": "Y", "group": "qwen",
    })

    def sort_key(r):
        try:
            p = float(r["params_short"].replace("M", "e6").replace("B", "e9").replace("K", "e3"))
        except:
            p = 999e9
        return (r["type"], p)

    rows.sort(key=sort_key)
    return rows


def build_readme(rows):
    lines = []
    lines.append("# Architecture Visualizers\n")
    lines.append("Interactive HTML visualizers for LLM architectures. "
                 "Generated by `generate_viz.py` from HuggingFace `config.json` (no weights needed).\n")
    lines.append("## Usage\n")
    lines.append("```bash")
    lines.append("python generate_viz.py Qwen/Qwen3-0.6B")
    lines.append("python generate_viz.py google/gemma-4-E2B-it")
    lines.append("python generate_viz.py tencent/Hy3 --subfolder checkpoint_folder_textonly")
    lines.append("```\n")

    lines.append(f"## All Visualizers ({len(rows)} models)\n")
    lines.append("| Model | Type | Params | Hidden | Layers | Q/KV | hd | Attn | QK-Norm | MLP | MoE | RoPE theta | Vocab | Tie |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append(
            f'| [{r["name"]}](./{r["file"]}) | `{r["type"]}` | {r["params"]} | {r["H"]} | '
            f'{r["layers"]} | {r["heads"]} | {r["head_dim"]} | {r["attn"]} | {r["qk"]} | '
            f'{r["mlp"]} | {r["moe"]} | {r["rope"]} | {r["vocab"]} | {r["tie"]} |'
        )

    lines.append("\n## Architecture Types\n")
    type_counts = {}
    for r in rows:
        type_counts.setdefault(r["type"], []).append(r["name"])
    lines.append("| Type | Count | Models |")
    lines.append("|---|---|---|")
    for t in sorted(type_counts.keys()):
        models = type_counts[t]
        display = ", ".join(models[:4])
        if len(models) > 4:
            display += f" +{len(models)-4} more"
        lines.append(f'| `{t}` | {len(models)} | {display} |')

    lines.append("\n## Key Architectural Differences\n")
    lines.append("| Feature | Models with it | Models without |")
    lines.append("|---|---|---|")
    qk_yes = [r["name"] for r in rows if r["qk"] == "Y"]
    lines.append(f'| **QK-Norm** | {len(qk_yes)} models | {len(rows)-len(qk_yes)} models |')
    mqa = [r["name"] for r in rows if r["attn"] == "MQA"]
    lines.append(f'| **MQA** (1 KV head) | {", ".join(mqa[:5])} | - |')
    gqa = [r for r in rows if "GQA" in r["attn"]]
    lines.append(f'| **GQA** | {len(gqa)} models | - |')
    mha = [r["name"] for r in rows if r["attn"] == "MHA"]
    lines.append(f'| **MHA** (no sharing) | {", ".join(mha[:5])} | - |')
    moe = [r for r in rows if r["moe"] != "-"]
    lines.append(f'| **MoE** | {len(moe)} models | {len(rows)-len(moe)} models |')
    geglu = [r["name"] for r in rows if r["mlp"] == "GeGLU"]
    lines.append(f'| **GeGLU** (GELU gated) | {", ".join(geglu[:5])} | - |')
    mlp_plain = [r["name"] for r in rows if r["mlp"] == "MLP"]
    if mlp_plain:
        lines.append(f'| **Plain MLP** (ReLU/ReLU2) | {", ".join(mlp_plain[:5])} | - |')

    lines.append("\n---\n")
    lines.append("## Hand-Crafted Reference\n")
    lines.append("`qwen3_0_6b_architecture_visualizer.html` is the original hand-crafted "
                 "visualizer for Qwen3-0.6B, built by fact-checking every value against the "
                 "HuggingFace config and source code. It has richer subgraphs than the generated files:\n")
    lines.append("- RMSNorm shows the full 8-step formula (x-square, mean, +eps, rsqrt, scale, weight)")
    lines.append("- RoPE shows the rotation matrix and frequency computation")
    lines.append("- QK-Norm explains the per-head normalization and why it's applied before RoPE")
    lines.append('- Every projection shows exact weight shapes and the "no bias" note')
    lines.append("- Embedding lookup explains weight tying (lm_head = embed_tokens)")
    lines.append("- Verified against `huggingface.co/Qwen/Qwen3-0.6B/raw/main/config.json` and HF source code\n")
    lines.append("All other `_viz.html` files are auto-generated by `generate_viz.py` from config.json alone. "
                 "They share the same template (`viz_template.html`) with values substituted per-model. "
                 "The hand-crafted version serves as the quality reference for what the generator aims to approximate.\n")

    lines.append("## How to Use\n")
    lines.append("### View the dashboard\n")
    lines.append("Open `index.html` in a browser. The split-view shows a searchable model list "
                 "on the left and the selected visualizer in an iframe on the right.\n")
    lines.append("- **Desktop** (>=768px): sidebar is always visible")
    lines.append("- **Mobile** (<768px): tap the Models button to open the sidebar as an overlay drawer")
    lines.append("- **Search**: type in the search box to filter by model name or architecture type")
    lines.append("- **Filters**: click Qwen / Google / DeepSeek / NVIDIA / Microsoft / Other")
    lines.append("- **Keyboard**: press Up/Down arrows to cycle through models")
    lines.append("- **Deep link**: append `#gemma-4-e2b` to the URL to open a specific model\n")
    lines.append("Each visualizer is a standalone interactive HTML file. Pan with drag, zoom with scroll, "
                 "click any node to drill into a subgraph. The Specs sidebar is toggleable on all screen sizes.\n")

    lines.append("### Add a new model\n")
    lines.append("**Step 1: Generate the visualizer**\n")
    lines.append("```bash")
    lines.append("python generate_viz.py Qwen/Qwen3-8B")
    lines.append("python generate_viz.py nvidia/Nemotron-Labs-Audex-2B --subfolder checkpoint_folder_textonly")
    lines.append("```\n")
    lines.append("The script only fetches `config.json` (a few KB). It auto-detects QK-Norm, "
                 "GQA/MQA/MHA, SwiGLU/GeGLU/ReLU2, MoE experts, RoPE theta, and nested configs.\n")
    lines.append("**Step 2: Register it in the dashboard**\n")
    lines.append("Open `index.html` and add one line to the `MODELS` array:\n")
    lines.append("```javascript")
    lines.append('{f:"Qwen_Qwen3-8B_viz.html",n:"Qwen3-8B",t:"qwen3",p:"8.2B",a:"GQA 4:1",q:"Y",m:"SwiGLU",g:"qwen",e:""},')
    lines.append("```\n")
    lines.append("**Step 3: Regenerate this README**\n")
    lines.append("```bash")
    lines.append("python generate_readme.py")
    lines.append("```\n")

    lines.append("### How the template works\n")
    lines.append("`viz_template.html` contains a single HTML page with JavaScript that reads a `CFG` JSON object "
                 "(injected by `generate_viz.py`) and builds the entire graph dynamically:\n")
    lines.append("- `buildNodes(CFG)` — creates the main graph nodes, conditionally adding QK-Norm / RoPE nodes")
    lines.append("- `buildEdges(layout)` — wires nodes with correct tensor shapes and routing")
    lines.append("- `getSubgraph(nodeId)` — returns a detailed subgraph for each clickable node")
    lines.append("- Rendering is shared across all models — only the `CFG` object changes\n")
    lines.append("The template uses `__CFG__`, `__SPECS__`, `__TITLE__`, `__MODEL_NAME__` as placeholders "
                 "that `generate_viz.py` replaces.")

    return "\n".join(lines) + "\n"


def main():
    rows = collect_models()
    readme = build_readme(rows)
    out = VIZ_DIR / "README.md"
    out.write_text(readme)
    print(f"Generated {out} ({len(rows)} models, {len(set(r['type'] for r in rows))} architecture types)")


if __name__ == "__main__":
    main()
