//! pmacros-derive — a `proc-macro = true` crate consumed by `pmacros-demo`.
//!
//! This is the SOURCE the `proc_macros` bundle documents (see
//! `pmacros-demo/PROC_MACROS.md`). It defines two DERIVE macros:
//!
//!   - `#[derive(Greet)]`       adds an inherent method `fn greet(&self) -> String`
//!   - `#[derive(FieldNames)]`  adds `fn field_names() -> &'static [&'static str]`
//!
//! `Greet` additionally accepts a derive helper attribute `#[greet(prefix = "...")]`,
//! declared via the `attributes(greet)` clause of `#[proc_macro_derive(...)]`.
//!
//! A proc-macro crate is a SEPARATE crate compiled as a dynamic library and
//! loaded by rustc; its macros "may not be used from the crate where they are
//! defined" (Rust Reference, Procedural macros). That is why this lives apart
//! from `pmacros-demo`. Each entry point is a plain Rust function
//! `fn(TokenStream) -> TokenStream` marked with `#[proc_macro_derive(Name, ...)]`.

use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, LitStr, parse_macro_input};

/// `#[derive(Greet)]` generates an inherent method
/// `pub fn greet(&self) -> String` returning the string `"<prefix>, <TypeName>!"`.
///
/// The prefix defaults to `"Hello"` and can be overridden with the derive
/// helper attribute `#[greet(prefix = "...")]` placed on the struct:
///
/// ```ignore
/// #[derive(Greet)]
/// #[greet(prefix = "Hi")]
/// struct Admin;
/// // Admin.greet() == "Hi, Admin!"
/// ```
#[proc_macro_derive(Greet, attributes(greet))]
pub fn derive_greet(input: TokenStream) -> TokenStream {
    // syn parses the compiler's TokenStream into a typed `DeriveInput`
    // (ident, generics, data, attrs). `parse_macro_input!` returns the parsed
    // value or emits a compile error and aborts on parse failure.
    let DeriveInput {
        ident,
        generics,
        attrs,
        ..
    } = parse_macro_input!(input as DeriveInput);

    // Split generics into `impl<...>`, `Type<...>`, and `where ...` fragments
    // so the generated impl has matching generic parameters. For a non-generic
    // type all three fragments are empty.
    let (impl_g, ty_g, where_g) = generics.split_for_impl();

    // Read the optional `#[greet(prefix = "...")]` helper attribute. The key is
    // parsed with syn 2's `parse_nested_meta`; an unknown key becomes a spanned
    // compile error via `syn::Error::to_compile_error`.
    let mut prefix = String::from("Hello");
    for attr in &attrs {
        if !attr.path().is_ident("greet") {
            continue;
        }
        if let Err(err) = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("prefix") {
                let lit: LitStr = meta.value()?.parse()?;
                prefix = lit.value();
                Ok(())
            } else {
                Err(meta.error("unsupported #[greet] key; expected `prefix`"))
            }
        }) {
            return err.to_compile_error().into();
        }
    }

    // quote! builds the output TokenStream by splicing the captured `#ident`
    // and `#prefix` into a template. Absolute paths (`::std::`, `::core::`) are
    // used because proc macros are UNHYGIENIC: the emitted tokens resolve in the
    // consumer's scope, so a bare `String`/`format!` could be shadowed there.
    let expanded = quote! {
        impl #impl_g #ident #ty_g #where_g {
            /// Generated by `#[derive(Greet)]`.
            pub fn greet(&self) -> ::std::string::String {
                ::std::format!("{}, {}!", #prefix, ::core::stringify!(#ident))
            }
        }
    };
    expanded.into()
}

/// `#[derive(FieldNames)]` generates an associated function
/// `pub fn field_names() -> &'static [&'static str]` listing the struct's named
/// fields in declaration order. Only structs with named fields are supported.
#[proc_macro_derive(FieldNames)]
pub fn derive_field_names(input: TokenStream) -> TokenStream {
    let DeriveInput {
        ident,
        generics,
        data,
        ..
    } = parse_macro_input!(input as DeriveInput);
    let (impl_g, ty_g, where_g) = generics.split_for_impl();

    // Walk the parsed struct to collect field idents. This is the core
    // capability that distinguishes a proc macro from `macro_rules!`: syn gives
    // a real AST the macro can inspect, not just an opaque token sequence.
    let field_idents: Vec<_> = match &data {
        Data::Struct(struct_data) => match &struct_data.fields {
            Fields::Named(named) => named.named.iter().filter_map(|f| f.ident.clone()).collect(),
            _ => {
                return syn::Error::new_spanned(
                    &ident,
                    "FieldNames only supports structs with named fields",
                )
                .to_compile_error()
                .into();
            }
        },
        _ => {
            return syn::Error::new_spanned(&ident, "FieldNames only supports structs")
                .to_compile_error()
                .into();
        }
    };

    // `#( ... ),*` in quote! is the repetition operator: it emits
    // `stringify!(field0), stringify!(field1), ...` once per captured ident.
    // Each `stringify!(#ident)` becomes a `&'static str` of the field's name.
    let expanded = quote! {
        impl #impl_g #ident #ty_g #where_g {
            /// Generated by `#[derive(FieldNames)]`.
            pub fn field_names() -> &'static [&'static str] {
                &[ #( ::core::stringify!(#field_idents) ),* ]
            }
        }
    };
    expanded.into()
}
