export {};

// Registry of bundles. The orchestrator updates this as each batch completes
// (workers do NOT edit this file — it is orchestrator-owned). Each entry links
// the interactive demo, the guide, and the ground-truth source.

interface Bundle {
  stem: string;          // unit_model
  guide: string;         // UNIT_MODEL.md
  title: string;         // "The symmetric unit"
  rfc: string;           // "§5.1"
  phase: string;         // "P0 — Anchor" | "P1" | "P2" | "P3" | "P4"
    blurb: string;
}

const BUNDLES: Bundle[] = [
  {
    stem: "unit_model",
    guide: "UNIT_MODEL.md",
    title: "The symmetric unit model",
    rfc: "§5.1",
    phase: "P0 — Anchor",
    blurb: "JSON is data, HTML is animation. Every unit (root + each slide) is a folder with index.html + index.json.",
  },
  // B1 — Document Model
  { stem: "root_index_json", guide: "ROOT_INDEX_JSON.md", title: "Root index.json", rfc: "§5.2", phase: "P1 — Document Model", blurb: "canvas · theme · audio · slide ordering. The root data file." },
  { stem: "slide_index_json", guide: "SLIDE_INDEX_JSON.md", title: "Slide index.json", rfc: "§5.3", phase: "P1 — Document Model", blurb: "fields · assets · voiceover · duration. The per-slide data file." },
  { stem: "data_binding", guide: "DATA_BINDING.md", title: "__FIELD__ data binding", rfc: "§5.6", phase: "P1 — Document Model", blurb: "How fields reach the HTML: __FIELD__ string replacement (stamping)." },
  { stem: "bare_template", guide: "BARE_TEMPLATE.md", title: "Bare <template> sub-comp", rfc: "§5.4–5.5", phase: "P1 — Document Model", blurb: "Why slide index.html is a bare <template>, not an <html> doc." },
  // B2 — Editor Surfaces
  { stem: "timeline_panel", guide: "TIMELINE_PANEL.md", title: "Timeline panel", rfc: "§7", phase: "P2 — Editor Surfaces", blurb: "Timeline = a view over (slide order + measured durations)." },
  { stem: "stage_canvas", guide: "STAGE_CANVAS.md", title: "Stage / canvas", rfc: "§7", phase: "P2 — Editor Surfaces", blurb: "The live preview surface rendering the active slide." },
  { stem: "properties_panel", guide: "PROPERTIES_PANEL.md", title: "Properties / data panel", rfc: "§7", phase: "P2 — Editor Surfaces", blurb: "Live-bind text fields → slide index.json (light DOM patch)." },
  { stem: "html_editor_surface", guide: "HTML_EDITOR_SURFACE.md", title: "HTML editor surface", rfc: "§7", phase: "P2 — Editor Surfaces", blurb: "Per-slide HTML editor — the Tier-2 AI surface — + lint gate." },
  // B3 — Preview & Render
  { stem: "slide_renderer_interface", guide: "SLIDE_RENDERER_INTERFACE.md", title: "SlideRenderer interface", rfc: "§9", phase: "P3 — Preview & Render", blurb: "load / render_at / duration — HF now, ours later, same interface." },
  { stem: "preview_engine", guide: "PREVIEW_ENGINE.md", title: "Preview engine", rfc: "§8", phase: "P3 — Preview & Render", blurb: "Drive GSAP timelines from the playhead (real-time, not frame-accurate)." },
  { stem: "audio_sync", guide: "AUDIO_SYNC.md", title: "Audio sync", rfc: "§8", phase: "P3 — Preview & Render", blurb: "External <audio> synced via timeupdate — bypasses player muting." },
  { stem: "captions_karaoke", guide: "CAPTIONS_KARAOKE.md", title: "Karaoke captions", rfc: "AGENTS.md", phase: "P3 — Preview & Render", blurb: "Word-level GSAP direct color tweens. NO transform/scale/font-size." },
  // B4 — Assets / Export / Determinism
  { stem: "asset_library", guide: "ASSET_LIBRARY.md", title: "Asset library (SHA-256)", rfc: "§5.1", phase: "P4 — Export & Determinism", blurb: "Content-addressed assets; drop → SHA ref lands in index.json." },
  { stem: "export_pipeline", guide: "EXPORT_PIPELINE.md", title: "Export pipeline", rfc: "§10", phase: "P4 — Export & Determinism", blurb: "Assemble + stamp + voiceover + captions → npx hyperframes render." },
  { stem: "visual_determinism", guide: "VISUAL_DETERMINISM.md", title: "Visual determinism", rfc: "§11", phase: "P4 — Export & Determinism", blurb: "Visual (not byte) determinism; perceptual hashing for edit diffs." },
];

const PHASE_ORDER = [
  "P0 — Anchor",
  "P1 — Document Model",
  "P2 — Editor Surfaces",
  "P3 — Preview & Render",
  "P4 — Export & Determinism",
];

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string,
  );
}

function existsFallback(href: string, label: string, cls: string): string {
  // All three artifacts share the stem; links are relative to repo root.
  return `<a class="lnk ${cls}" href="${href}">${label}</a>`;
}

function card(b: Bundle): string {
  const demo = `bundles/${b.stem}.html`;
  const guide = `bundles/${b.guide}`;
  const src = `bundles/${b.stem}.ts`;
  return `
    <article class="card">
      <header>
        <span class="rfc">${escapeHtml(b.rfc)}</span>
        <h3>${escapeHtml(b.title)}</h3>
        <code class="stem">${escapeHtml(b.stem)}</code>
      </header>
      <p>${escapeHtml(b.blurb)}</p>
      <div class="links">
        ${existsFallback(demo, "▶ demo", "demo")}
        ${existsFallback(guide, "📖 guide", "guide")}
        ${existsFallback(src, "📄 src", "src")}
      </div>
    </article>`;
}

function render(): void {
  const app = document.getElementById("app");
  if (!app) return;
  const byPhase = PHASE_ORDER.map((p) => ({
    phase: p,
    items: BUNDLES.filter((b) => b.phase === p),
  }));

  const total = BUNDLES.length;
  const html = `
    <header class="hero">
      <h1>ovk-web</h1>
      <p class="tag">From <code>pnpm create vite</code> → a Google-Vids-class scene editor.</p>
      <p class="tag">A concept-builder curriculum walking RFC 0001 one verified idea at a time. ${total} concepts · every claim printed by a runnable <code>.ts</code> · every demo gold-checked.</p>
      <div class="hero-links">
        <a class="lnk guide" href="HOW_TO_RESEARCH.md">📖 HOW_TO_RESEARCH</a>
        <a class="lnk src" href="TODO.md">📋 TODO</a>
        <a class="lnk src" href="docs/rfc-0001.md">📜 RFC 0001</a>
      </div>
    </header>
    ${byPhase
      .map(
        (row) => `
      <section class="phase">
        <h2>${escapeHtml(row.phase)} <span class="count">${row.items.length}</span></h2>
        <div class="grid">
          ${row.items.map(card).join("")}
        </div>
      </section>`,
      )
      .join("")}
  `;
  app.innerHTML = html;
}

render();
