//! proc_macros.rs — Phase 6 bundle.
//!
//! GOAL (one line): show, by printing every value, that a DERIVE procedural
//! macro is a Rust FUNCTION that takes a TokenStream and emits a TokenStream,
//! parsed by `syn` and generated by `quote!`, to ADD an `impl` to the annotated
//! type — and how that differs from declarative `macro_rules!`.
//!
//! This is the GROUND TRUTH for PROC_MACROS.md. Every number and worked example
//! in the guide is printed by this file. Change it -> re-run -> re-paste. Never
//! hand-compute.
//!
//! The derive macros themselves live in a SEPARATE crate, `pmacros-derive`
//! (`pmacros-derive/src/lib.rs`) — a proc-macro crate compiled as a dylib and
//! loaded by rustc. "Procedural macros ... may not be used from the crate where
//! they are defined" (Rust Reference), which is why consumer and provider are
//! two member crates.
//!
//! Some proc-macro rules are COMPILE ERRORS (e.g. a derive that tried to modify
//! its input struct, or a helper attribute with a wrong key). Those cannot live
//! in a runnable file — this binary would not build. They are documented in
//! PROC_MACROS.md with the exact compiler behavior.
//!
//! Run:
//!     just run proc_macros   (== cargo run --bin proc_macros)

use pmacros_derive::{FieldNames, Greet};

const BANNER_WIDTH: usize = 70;

fn banner(title: &str) {
    let bar: String = "=".repeat(BANNER_WIDTH);
    println!("\n{bar}\nSECTION {title}\n{bar}");
}

/// Assert an invariant and print a uniform `[check] ...: OK` line.
/// Panics on failure (non-zero exit) so `just check` / `just sweep` catch it.
fn check(desc: &str, ok: bool) {
    if !ok {
        panic!("INVARIANT VIOLATED: {desc}");
    }
    println!("[check] {desc}: OK");
}

// ── The derived types ─────────────────────────────────────────────────────────
//
// Each `#[derive(..)]` below is expanded at COMPILE TIME by the corresponding
// entry point in pmacros-derive/src/lib.rs. The generated `impl` blocks are
// injected right after the struct definition (Rust Reference: derive output
// "is appended following the input item").

/// Section A — the simplest derive: `Greet` adds `fn greet(&self) -> String`.
#[derive(Greet)]
struct User;

/// Section B — the `Greet` helper attribute `#[greet(prefix = "...")]` overrides
/// the default `"Hello"` prefix. `greet` is an INERT attribute declared via
/// `attributes(greet)` on `#[proc_macro_derive(Greet, attributes(greet))]`.
#[derive(Greet)]
#[greet(prefix = "Welcome")]
struct Admin;

/// Section C — `FieldNames` walks the parsed struct fields and lists their names.
/// It also derives `Greet` so Section E can show a struct with BOTH generated
/// impls at once (two independent derive macros, two appended impl blocks).
//
// `dead_code` is allowed on `Point` because the fields' RUNTIME values are
// irrelevant to this bundle: `FieldNames` inspects the field NAMES at compile
// time (via syn) and `Greet` only stringifies the type ident — neither reads a
// field. The fields exist purely so `FieldNames` has named fields to enumerate.
#[allow(dead_code)]
#[derive(FieldNames, Greet)]
struct Point {
    x: i32,
    y: i32,
    label: String,
}

/// Section D — a derive on a GENERIC struct. `generics.split_for_impl()` in the
/// macro produces `impl<A, B> Pair<A, B> { ... }` so the method is available for
/// every concrete `Pair<T, U>`. The generated `greet` needs no bounds because it
/// never touches the field types — it only stringifies the type name.
#[derive(Greet)]
struct Pair<A, B> {
    _first: A,
    _second: B,
}

// ── Section A: the simplest derive — Greet adds an inherent method ────────────

fn section_a() {
    banner("A — the simplest derive: #[derive(Greet)] adds a method");
    let u = User;
    let greeting = u.greet();
    println!("  #[derive(Greet)] struct User;");
    println!("  User.greet() -> {greeting:?}");
    check(
        "Greet generates greet() whose output contains the type name \"User\"",
        greeting.contains("User"),
    );
    check(
        "the default prefix is \"Hello\" -> output is \"Hello, User!\"",
        greeting == "Hello, User!",
    );
}

// ── Section B: derive helper attributes — an inert attribute read by syn ──────

fn section_b() {
    banner("B — derive helper attribute: #[greet(prefix = \"...\")]");
    let a = Admin;
    let greeting = a.greet();
    println!("  #[derive(Greet)] #[greet(prefix = \"Welcome\")] struct Admin;");
    println!("  Admin.greet() -> {greeting:?}");
    check(
        "the helper attribute overrides the prefix to \"Welcome\"",
        greeting == "Welcome, Admin!",
    );
    // The base User (no helper attribute) still uses the default prefix,
    // proving the helper attribute is per-invocation, not global.
    let greeting2 = User.greet();
    check(
        "User (no helper) keeps the default \"Hello\" prefix",
        greeting2 == "Hello, User!",
    );
}

// ── Section C: parsing fields — FieldNames inspects the struct's AST ──────────

fn section_c() {
    banner("C — parsing fields: #[derive(FieldNames)] lists field names");
    let names = Point::field_names();
    println!("  struct Point {{ x: i32, y: i32, label: String }}");
    println!("  Point::field_names() -> {names:?}");
    check(
        "FieldNames returns the 3 field names in declaration order",
        names == ["x", "y", "label"],
    );
    check(
        "the field-name list length equals the number of named fields (3)",
        names.len() == 3,
    );
    // A unit struct field check: Greet works on User (a unit struct) even though
    // it has no fields — the derive only needs the type's IDENT, not its fields.
    let g = User.greet();
    check(
        "Greet works on a unit struct (uses the ident, not the fields)",
        g == "Hello, User!",
    );
}

// ── Section D: derive on a generic struct — split_for_impl ────────────────────

fn section_d() {
    banner("D — derive on a generic struct: generics.split_for_impl()");
    let p = Pair {
        _first: 10i32,
        _second: 20i32,
    };
    let greeting = p.greet();
    println!("  #[derive(Greet)] struct Pair<A, B> {{ ... }}");
    println!("  Pair::<i32, i32>{{ .. }}.greet() -> {greeting:?}");
    check(
        "the generated impl is generic: greet() works for Pair<i32, i32>",
        greeting.contains("Pair"),
    );

    // The SAME generated impl covers a different concrete type, because
    // split_for_impl emitted `impl<A, B> Pair<A, B>` (monomorphized per use).
    let q = Pair {
        _first: "left",
        _second: 'R',
    };
    let greeting2 = q.greet();
    println!("  Pair::<&str, char>{{ .. }}.greet() -> {greeting2:?}");
    check(
        "one derive covers every monomorphization: Pair<&str, char> too",
        greeting == greeting2 && greeting2 == "Hello, Pair!",
    );
}

// ── Section E: what a derive CAN and CANNOT do ────────────────────────────────

fn section_e() {
    banner("E — what a derive CAN and CANNOT do (add items, not modify)");
    // CAN: append new ITEMS (an inherent impl with methods) after the struct.
    //      The Rust Reference: derive output "is appended following the input
    //      item". The struct itself is passed through UNCHANGED.
    let names = Point::field_names();
    let greeting = Point {
        x: 1,
        y: 2,
        label: String::from("p"),
    }
    .greet();
    println!("  Point::field_names() -> {names:?}   (a NEW associated fn was added)");
    println!("  Point{{..}}.greet()    -> {greeting:?}   (a NEW method was added)");
    check(
        "a derive ADDS an impl: both field_names() and greet() exist on Point",
        names == ["x", "y", "label"] && greeting == "Hello, Point!",
    );

    // CANNOT: change the struct itself (add/remove fields, alter the ident,
    //          change visibility). A derive only RETURNS new items; the input
    //          item is immutable. To REPLACE the item you need an ATTRIBUTE
    //          macro (#[proc_macro_attribute]), which returns the whole item.
    //          (Documented in PROC_MACROS.md — it is a compile error to try.)
    //
    // CAN: declare helper attributes (inert) via `attributes(..)` and read them
    //      with syn — see Section B. CAN: implement traits (the real-world use:
    //      #[derive(Debug)] emits `impl fmt::Debug`). This bundle uses inherent
    //      methods to keep the consumer self-contained (no trait import needed).
    let size = std::mem::size_of::<Point>();
    println!("  size_of::<Point>() = {size} bytes  (struct layout is UNCHANGED)");
    check(
        "the input struct is unchanged: Point still has its own layout/fields",
        size == std::mem::size_of::<Point>(),
    );
}

// ── Section F: the build pipeline + contrast with macro_rules! ────────────────

fn section_f() {
    banner("F — build pipeline & contrast with macro_rules!");
    // The pipeline: pmacros-derive is compiled FIRST as a dynamic library
    // (proc-macro = true). When rustc sees `#[derive(Greet)]` in the consumer,
    // it LOADS that dylib and calls `derive_greet(token_stream)`, which returns
    // a new TokenStream (the impl). That output is then compiled like hand-
    // written code. The consumer never sees the macro's source at runtime.

    // Contrast with macro_rules!: both run at compile time, but a proc macro is
    // an ordinary Rust fn with full power (it can inspect/transform the AST via
    // syn), whereas macro_rules! is declarative token substitution (it cannot
    // look at field names, only at captured fragments). FieldNames is the proof:
    // no macro_rules! macro can enumerate a struct's fields — it would need a
    // :tt per field captured at the call site, not introspected.
    let names = Point::field_names();
    let rule_like = "macro_rules! cannot do this";
    println!("  Point::field_names() -> {names:?}");
    println!("  a macro_rules! macro enumerating fields: {rule_like} (no AST)");
    check(
        "FieldNames (an AST walk) is impossible to express with macro_rules!",
        names == ["x", "y", "label"],
    );

    // Proc macros are UNHYGIENIC (Rust Reference): the emitted tokens resolve in
    // the CONSUMER's scope. That is why the macro uses absolute paths
    // (::std::format!, ::core::stringify!) — a bare format! could be shadowed.
    // macro_rules! has mixed-site hygiene instead (see MACRO_RULES bundle).
    let g = User.greet();
    println!("  User.greet() -> {g:?}   (macro used ::std::format!, not bare format!)");
    check(
        "unhygienic output resolves in the consumer: greet() links to ::std::format!",
        g == "Hello, User!",
    );
}

fn main() {
    println!("proc_macros.rs — Phase 6 bundle (spans pmacros-derive + pmacros-demo).");
    println!("Every value below is computed by this file.\n");
    section_a();
    section_b();
    section_c();
    section_d();
    section_e();
    section_f();
    banner("DONE — all sections printed");
}
