"""
synthetic_curation.py - Reference implementation of the Cosmopedia-style
synthetic-textbook generation pipeline (the Phi "Textbooks Are All You Need" recipe).

This is the single source of truth that SYNTHETIC_CURATION.md is built from. Every
number, table, and worked example in the guide is printed by this file. If you
change something here, re-run and re-paste the output into the guide.

Run:
    uv run python synthetic_curation.py

== The big idea, in one paragraph (no math) ==================================
Small models (Phi-1, SmolLM) punch above their parameter weight NOT by hoovering
up more raw web data, but by training on a small amount of extremely high-quality
synthetic "textbooks". Phi-1 (1.3B params) trained on just 7B tokens -- 6B filtered
"textbook-quality" web + 1B synthetic textbooks/exercises generated by GPT-3.5 --
and beat models 100x its size on code (HumanEval 50.6%). The Cosmopedia recipe
makes that synthetic pipeline OPEN: cluster real web -> seed a topic distribution ->
attach a persona + style system prompt -> generate -> quality-filter + dedup ->
a corpus that "teaches" the model rather than just exposing it to text. Quality of
data, not quantity, is the single biggest lever for SLM capability.

== IMPORTANT -- this is a FAITHFUL PIPELINE SIMULATION =========================
We do NOT call a real LLM and we do NOT touch the network. Instead we model EACH
STAGE of the Cosmopedia pipeline and the QUALITY METRICS measured over its outputs,
using deterministic template expansion. The pipeline STAGES and the METRICS
(type-token ratio, sentence length, topic coverage, benchmark-contamination flag)
are REAL and EXACT; only the free-text "generation" is simulated (exactly as
../llm/zero.py simulates a distributed cluster single-process). The point is to
make every stage and every metric printable and reproducible on a laptop.

== The lineage (old -> new, with WHY) =========================================
  scraped web (RefinedWeb/FineWeb) : abundant but NOISY, uneven quality, and
                 BENCHMARK-CONTAMINATED (MMLU/HellaSwag questions leak in). More
                 tokens help, but quality plateaus and contamination inflates
                 benchmark scores without real capability.
  -> Phi "Textbooks Are All You Need" : curated "textbook-quality" web (6B) +
                 synthetic textbooks/exercises via GPT-3.5 (1B) -> 1.3B model beats
                 giants on code. Lesson: a little clean data >> a lot of dirty data.
  -> Cosmopedia pipeline : the OPEN replication of Phi-1.5's synthetic corpus.
                 cluster real web (145 clusters) -> seed 20K topics -> persona +
                 style system prompt (4 audiences x 3 styles = 12x prompt mult) ->
                 generate 25B+ tokens with Mixtral-8x7B -> quality-filter +
                 decontaminate + dedup. SLMs (SmolLM) get a large slice of their
                 capability from this synthetic share of the mix.

== Plain-English glossary =====================================================
    seed sample   a real web/curated page used to GROUND a synthetic generation
                  (keeps output on-topic; Cosmopedia conditions on it ~50% of time).
    topic         the subject a textbook is about (BISAC category / cluster label).
    cluster       a group of similar web docs; its label becomes a seed topic.
    persona       the "voice" generating the text (professor, storyteller, tutor).
                  Cosmopedia uses 4 audiences: young children, high school, college,
                  researchers.
    style         the FORMAT (textbook, blog post, wikiHow). 3 styles in Cosmopedia.
    prompt mult.  4 audiences x 3 styles = 12 distinct prompts per topic -> more
                  diversity from one topic without extra seed data.
    generation    the act of producing the textbook text from the prompt (here:
                  deterministic template expansion; in Cosmopedia: Mixtral-8x7B).
    TTR           type-token ratio = unique_tokens / total_tokens. A vocabulary-
                  density proxy: a richer persona -> more distinct words -> higher
                  TTR. Used to compare generation quality across personas.
    coverage      fraction of seed topics actually touched by the generated corpus.
                  Low coverage -> the model sees a skewed world.
    decontam.     removing benchmark questions (MMLU, HellaSwag, ...) that leaked
                  into seed samples, so eval scores reflect real capability.
    dedup         removing near-duplicate generations (mode collapse). Cosmopedia
                  achieves <1% duplicates. (See 🔗 MINHASH_DEDUP.)
"""

from __future__ import annotations

import re

import torch

torch.set_printoptions(precision=4, sci_mode=False)

BANNER = "=" * 72


# ----------------------------------------------------------------------------
# PRETTY PRINTERS + check() helper (no raw assert -- assert is compiled out by -O)
# ----------------------------------------------------------------------------

def banner(title: str):
    print()
    print(BANNER)
    print(f"  {title}")
    print(BANNER)


def check(desc: str, ok: bool):
    """Print '[check] desc: OK' and exit non-zero on failure (assert is unsafe)."""
    print(f"  [check] {desc}: {'OK' if ok else 'FAIL'}")
    if not ok:
        raise SystemExit(f"CHECK FAILED: {desc}")


# ============================================================================
# 0. THE PIPELINE PRIMITIVES (the Cosmopedia stages, simulated deterministically)
#    These are the building blocks every section below calls.
# ============================================================================

# --- A fixed seed-topic distribution (Cosmopedia v1 used 145 web clusters -> 112
#     retained; v2 used 34,000 BISAC topics. Here: 8 topics with target weights.)
SEED_TOPICS = [
    ("algebra",            12),
    ("biology",            14),
    ("world_history",       9),
    ("computer_science",   16),
    ("civics",              7),
    ("geometry",           10),
    ("chemistry",          11),
    ("literature",          8),
]
TOPICS = [t for t, _ in SEED_TOPICS]
TOPIC_WEIGHTS = [w for _, w in SEED_TOPICS]


# --- The persona taxonomy (Cosmopedia audiences: young children / high school /
#     college / researchers; here 3 personas spanning terse -> rich).
#     Each persona ships an INTRO phrase and an ADJECTIVE pool. The pool is what
#     drives vocabulary density (TTR): a richer pool -> more distinct words.
PERSONAS = {
    "baseline_bot": {
        "intro": "Here is info on",
        "adjectives": ["basic", "simple", "common", "general"],          # 4 words
    },
    "patient_professor": {
        "intro": "Let us explore",
        "adjectives": ["intricate", "rigorous", "foundational", "nuanced",
                       "systematic", "comprehensive", "profound", "elaborate"],  # 8
    },
    "engaging_storyteller": {
        "intro": "Picture the world of",
        "adjectives": ["vivid", "lively", "curious", "bright",
                       "bold", "warm", "striking", "memorable"],          # 8
    },
}

# --- The style taxonomy (Cosmopedia styles: textbook / blog post / wikiHow; 3).
STYLES = {
    "academic_textbook": "a rigorous academic textbook",
    "blog_post":         "an accessible blog post",
}


def build_prompt(topic: str, persona: str, style: str) -> str:
    """Construct the Cosmopedia-style system+user prompt (3 components:
    topic + seed + generation style). Returns ONE string for printing."""
    style_label = STYLES[style]
    return (
        f"[system] You are a {persona.replace('_', ' ')}. Write {style_label} "
        f"section.\n"
        f"[user]   Topic: {topic}. Seed sample: <a grounded web excerpt on "
        f"{topic}>. Audience: {persona.replace('_', ' ')}. Style: {style_label}.\n"
        f"         Produce an intro, a definition, an example, and an exercise."
    )


def cap(topic: str) -> str:
    """Capitalize the first character of a topic for sentence starts."""
    return topic[0].upper() + topic[1:]


def generate_section(topic: str, persona: str, style: str, seed: int = 42) -> str:
    """SIMULATED generation: deterministically expand the prompt into a mock
    textbook section.

    The scaffold is FIXED across personas; the persona's adjective POOL fills 8
    slots. Slot i picks `pool[(seed + i) % len(pool)]` -- a deterministic, seed-
    reproducible choice (no library RNG, so JS reproduces it byte-for-byte). A
    persona with a SMALL pool repeats words (low TTR); a persona with a RICH pool
    uses distinct words (high TTR). That contrast IS the lesson: richer prompting
    begets richer vocabulary in the synthetic corpus.

    NOTE: style does not change the scaffold here (it would in a real LLM); it is
    kept as a parameter so the pipeline shape matches Cosmopedia exactly.
    """
    pool = PERSONAS[persona]["adjectives"]
    intro = PERSONAS[persona]["intro"]
    slots = [pool[(seed + i) % len(pool)] for i in range(8)]
    s0, s1, s2, s3, s4, s5, s6, s7 = slots
    T = cap(topic)
    return (
        f"{intro} {topic}. "
        f"{T} is a {s0}, {s1} subject. "
        f"Its {s2} and {s3} features matter. "
        f"Students find the {s4}, {s5} parts clear. "
        f"Exercise: review the {s6} and {s7} sections."
    )


# --- tokenization (kept trivial so JS reproduces it exactly): lowercase, strip a
#     fixed punctuation set, split on whitespace.
_PUNCT = '.,;:!?"()[]{}'
_PUNCT_TRANS = str.maketrans({c: " " for c in _PUNCT})


def tokenize(text: str) -> list[str]:
    """Lowercase, drop punctuation, split on whitespace. Deterministic + JS-portable."""
    cleaned = text.lower().translate(_PUNCT_TRANS)
    return [t for t in cleaned.split() if t]


def type_token_ratio(text: str) -> float:
    """TTR = unique tokens / total tokens. A vocabulary-density proxy."""
    toks = tokenize(text)
    if not toks:
        return 0.0
    return len(set(toks)) / len(toks)


def avg_sentence_length(text: str) -> float:
    """Average tokens per sentence (sentences split on '. ')."""
    sentences = [s for s in text.split(".") if s.strip()]
    if not sentences:
        return 0.0
    lengths = [len(tokenize(s)) for s in sentences]
    return sum(lengths) / len(lengths)


# --- benchmark-contamination filter (Cosmopedia decontaminates against these).
BENCHMARK_BLOCKLIST = [
    "MMLU", "HellaSwag", "PIQA", "ARC", "WinoGrande", "OpenBookQA",
    "HumanEval", "MBPP", "BoolQ", "SIQA", "TruthfulQA",
]
_CONTAM_RE = re.compile(r"\b(" + "|".join(BENCHMARK_BLOCKLIST) + r")\b")


def is_contaminated(text: str) -> bool:
    """Flag a sample that names a benchmark (regex blocklist).

    Cosmopedia's real decontamination is stricter: 10-gram overlap -> difflib
    SequenceMatcher ratio > 0.5 -> discard. This regex is a fast first-pass filter
    on the benchmark NAMES that most often leak; it catches the headline case
    (a sample literally containing 'MMLU') deterministically.
    """
    return bool(_CONTAM_RE.search(text))


# ============================================================================
# A. TOPIC SEED DISTRIBUTION  -- cluster real web -> a topic distribution
#    Goal: COVERAGE across domains. A skewed distribution -> a skewed model.
# ============================================================================

def section_topic_distribution():
    banner("SECTION A: topic seed distribution -- coverage is the goal")
    total_w = sum(TOPIC_WEIGHTS)
    print(f"Seed topics: {len(TOPICS)}, total target weight = {total_w}\n")
    print("| topic             | weight | share  |")
    print("|-------------------|--------|--------|")
    for t, w in SEED_TOPICS:
        print(f"| {t:<17} | {w:>6} | {w / total_w * 100:>5.1f}% |")
    print()
    # seeded weighted sampling (torch.multinomial -> deterministic given the seed)
    g = torch.Generator().manual_seed(42)
    idx = torch.multinomial(torch.tensor(TOPIC_WEIGHTS, dtype=torch.float32),
                            num_samples=40, replacement=True, generator=g)
    batch = [TOPICS[i] for i in idx.tolist()]
    counts = {t: 0 for t in TOPICS}
    for t in batch:
        counts[t] += 1
    covered = sum(1 for t in TOPICS if counts[t] > 0)
    coverage = covered / len(TOPICS)
    print("Seeded sample (n=40, seed=42) topic counts:\n")
    print("| topic             | drawn |")
    print("|-------------------|-------|")
    for t in TOPICS:
        print(f"| {t:<17} | {counts[t]:>5} |")
    print()
    print(f"  coverage = {covered}/{len(TOPICS)} topics touched = {coverage:.1%}")
    check("coverage is 100% (all topics sampled at least once)", covered == len(TOPICS))
    check("weighted draw favors the heaviest topic (computer_science, w=16)",
          counts["computer_science"] >= counts["civics"])
    return coverage


# ============================================================================
# B. PERSONA + STYLE PROMPT CONSTRUCTION  -- the Cosmopedia prompt = 3 components
# ============================================================================

def section_prompt_construction():
    banner("SECTION B: persona + style system prompt (Cosmopedia = topic+seed+style)")
    print("A Cosmopedia prompt has THREE components (verified, see _reference.txt):")
    print("  (1) the TOPIC          (cluster label / BISAC category)")
    print("  (2) the SEED SAMPLE    (a real web/curated page that grounds the output)")
    print("  (3) the GEN. STYLE     (audience + format)\n")
    print("Cosmopedia prompt multiplication: 4 audiences x 3 styles = 12 prompts/topic.")
    aud, sty = 4, 3
    print(f"  {aud} audiences x {sty} styles = {aud * sty}x distinct prompts per topic")
    check("Cosmopedia prompt multiplication is 4x3=12", aud * sty == 12)
    print()
    print("Our toy taxonomy (3 personas x 2 styles):\n")
    print("| persona              | style              |")
    print("|----------------------|--------------------|")
    for p in PERSONAS:
        for s in STYLES:
            print(f"| {p:<20} | {s:<18} |")
    print(f"\n  -> {len(PERSONAS)} personas x {len(STYLES)} styles = "
          f"{len(PERSONAS) * len(STYLES)} (topic, persona, style) tuples per topic\n")
    # print TWO full example prompts to show the template
    for (t, p, s) in [("biology", "patient_professor", "academic_textbook"),
                      ("algebra", "engaging_storyteller", "blog_post")]:
        print(f"--- full prompt for (topic={t}, persona={p}, style={s}) ---")
        print(build_prompt(t, p, s))
        print()
    check("build_prompt names the topic, seed, audience, and style",
          all(k in build_prompt("biology", "patient_professor", "academic_textbook")
              for k in ("biology", "Seed sample", "patient professor",
                        "academic textbook")))


# ============================================================================
# C. SIMULATED GENERATION  -- deterministic template expansion (NO LLM call)
#    The GOLD ANCHOR pair is pinned here: (photosynthesis, patient_professor,
#    academic_textbook, seed=42). Its text + TTR are recomputed by the .html.
# ============================================================================

GOLD_TOPIC = "photosynthesis"
GOLD_PERSONA = "patient_professor"
GOLD_STYLE = "academic_textbook"
GOLD_SEED = 42


def section_simulated_generation():
    banner("SECTION C: SIMULATED generation (deterministic template expansion)")
    print("We do NOT call an LLM. generate_section() fills a fixed scaffold with")
    print("words drawn from the persona's adjective pool by slot i = "
          "pool[(seed+i) % len(pool)].\n")
    print("Three personas over the SAME topic (algebra), seed=42:\n")
    print("| persona              | pool size | sample generation (truncated) |")
    print("|----------------------|-----------|-------------------------------|")
    for p in PERSONAS:
        text = generate_section("algebra", p, "academic_textbook", GOLD_SEED)
        pool_n = len(PERSONAS[p]["adjectives"])
        print(f"| {p:<20} | {pool_n:>9} | {text[:62]}... |")
    print()
    print("--- GOLD ANCHOR (pinned for synthetic_curation.html) ---")
    print(f"  (topic={GOLD_TOPIC}, persona={GOLD_PERSONA}, "
          f"style={GOLD_STYLE}, seed={GOLD_SEED})\n")
    gold_text = generate_section(GOLD_TOPIC, GOLD_PERSONA, GOLD_STYLE, GOLD_SEED)
    print(f"  full generated section:\n    \"{gold_text}\"\n")
    gold_tokens = tokenize(gold_text)
    gold_ttr = type_token_ratio(gold_text)
    print(f"  tokens     = {len(gold_tokens)}")
    print(f"  unique     = {len(set(gold_tokens))}")
    print(f"  TTR        = {gold_ttr:.4f}")
    print(f"\n  GOLD PIN: TTR = {gold_ttr:.4f}  (the .html recomputes this)\n")
    check("GOLD TTR is in (0,1] and computed from >0 tokens",
          0 < gold_ttr <= 1.0 and len(gold_tokens) > 0)
    return gold_text, gold_ttr


# ============================================================================
# D. QUALITY METRICS + DECONTAMINATION  -- TTR, sentence length, coverage, flag
# ============================================================================

def section_quality_metrics():
    banner("SECTION D: quality metrics + benchmark decontamination")
    # --- D.1: TTR across personas (the headline: richer persona -> higher TTR) ---
    print("D.1  type-token ratio across personas (topic=algebra, seed=42):\n")
    print("| persona              | pool | tokens | unique | TTR    |")
    print("|----------------------|------|--------|--------|--------|")
    ttr_by_persona = {}
    for p in PERSONAS:
        text = generate_section("algebra", p, "academic_textbook", GOLD_SEED)
        toks = tokenize(text)
        ttr = type_token_ratio(text)
        ttr_by_persona[p] = ttr
        print(f"| {p:<20} | {len(PERSONAS[p]['adjectives']):>4} | {len(toks):>6} | "
              f"{len(set(toks)):>6} | {ttr:>6.4f} |")
    print()
    prof_ttr = ttr_by_persona["patient_professor"]
    base_ttr = ttr_by_persona["baseline_bot"]
    print(f"  patient_professor TTR = {prof_ttr:.4f}")
    print(f"  baseline_bot     TTR = {base_ttr:.4f}")
    print(f"  delta = +{prof_ttr - base_ttr:.4f}  (richer pool -> higher vocabulary density)")
    check("TTR(patient_professor) > TTR(baseline_bot)", prof_ttr > base_ttr)
    check("storyteller TTR > baseline too",
          ttr_by_persona["engaging_storyteller"] > base_ttr)

    # --- D.2: avg sentence length (a style proxy) ---
    print("\nD.2  average sentence length (tokens/sentence):\n")
    print("| persona              | avg sentence len |")
    print("|----------------------|------------------|")
    for p in PERSONAS:
        text = generate_section("biology", p, "academic_textbook", GOLD_SEED)
        asl = avg_sentence_length(text)
        print(f"| {p:<20} | {asl:>16.2f} |")

    # --- D.3: corpus coverage (generate across all topics, 1 persona) ---
    print("\nD.3  corpus coverage -- generate one section per topic, one persona:\n")
    covered = 0
    for t in TOPICS:
        text = generate_section(t, "patient_professor", "academic_textbook", GOLD_SEED)
        covered += 1 if len(tokenize(text)) > 0 else 0
    coverage = covered / len(TOPICS)
    print(f"  topics touched = {covered}/{len(TOPICS)} = {coverage:.1%}")
    check("corpus coverage is 100% (every seed topic generated)", coverage == 1.0)

    # --- D.4: benchmark decontamination ---
    print("\nD.4  benchmark decontamination (regex blocklist):\n")
    print(f"  blocklist = {BENCHMARK_BLOCKLIST}\n")
    clean = generate_section("chemistry", "patient_professor", "academic_textbook",
                             GOLD_SEED)
    contaminated = ("This fine chapter is like an MMLU question and a HellaSwag "
                    "story mixed together.")
    print(f"  clean sample      -> is_contaminated = {is_contaminated(clean)}")
    print(f"  contaminated (has 'MMLU') -> is_contaminated = "
          f"{is_contaminated(contaminated)}\n")
    check("clean synthetic section is NOT flagged", is_contaminated(clean) is False)
    check("sample containing 'MMLU' is flagged contaminated (True)",
          is_contaminated(contaminated) is True)
    check("PIQA / WinoGrande / ARC also caught by the blocklist",
          is_contaminated("see PIQA") and is_contaminated("WinoGrande leaks")
          and is_contaminated("ARC challenge"))


# ============================================================================
# E. THE LINEAGE + WORKED RECAP (pinned gold for synthetic_curation.html)
# ============================================================================

def section_lineage_recap(gold_text: str, gold_ttr: float):
    banner("SECTION E: lineage recap + the pinned GOLD value")
    print("scraped web  ->  Phi textbooks  ->  Cosmopedia pipeline:\n")
    print("| stage            | what it does                         |")
    print("|------------------|--------------------------------------|")
    lineage = [
        ("scraped web",     "noisy, uneven, benchmark-contaminated"),
        ("Phi textbooks",   "curated 'textbook-quality' + synthetic (7B tok)"),
        ("cluster topics",  "group web docs -> seed-topic distribution"),
        ("persona+style",   "4 audiences x 3 styles = 12x prompt mult."),
        ("generate",        "Mixtral-8x7B -> 25B+ tokens (simulated here)"),
        ("filter+dedup",    "decontaminate benchmarks; <1% duplicates"),
    ]
    for name, what in lineage:
        print(f"| {name:<16} | {what:<36} |")
    print()
    print("GOLD pinned for synthetic_curation.html "
          f"(topic={GOLD_TOPIC}, persona={GOLD_PERSONA}, seed={GOLD_SEED}):")
    print(f"  generated text = \"{gold_text}\"")
    print(f"  TTR            = {gold_ttr:.4f}")
    check("GOLD TTR reproduces deterministically",
          abs(type_token_ratio(generate_section(GOLD_TOPIC, GOLD_PERSONA,
                                                GOLD_STYLE, GOLD_SEED)) - gold_ttr)
          < 1e-12)


# ============================================================================
# main
# ============================================================================

def main():
    print("synthetic_curation.py - the Cosmopedia-style synthetic-textbook pipeline.\n"
          "All numbers below feed SYNTHETIC_CURATION.md.  torch =", torch.__version__)
    print("\nNOTE: no LLM API is called. Generation is deterministic template\n"
          "expansion; the PIPELINE STAGES and QUALITY METRICS are real and exact.\n"
          "This models the recipe, not the free text (like ../llm/zero.py models a\n"
          "distributed cluster single-process).")

    section_topic_distribution()
    section_prompt_construction()
    gold_text, gold_ttr = section_simulated_generation()
    section_quality_metrics()
    section_lineage_recap(gold_text, gold_ttr)

    banner("DONE - all sections printed, all [check]s passed")


if __name__ == "__main__":
    main()
